[server]
protocol = http
http_addr = 0.0.0.0
http_port = 3000
domain = localhost
root_url = %(domain)s:%(http_port)s/
enable_gzip = true

[database]
type = postgres
host = postgres:5432
name = grafana
user = grafana
password = grafana
ssl_mode = disable

[security]
admin_user = admin
admin_password = admin123
secret_key = SW2YcwTIb9zpOOhoPsMm
disable_gravatar = true

[users]
allow_sign_up = false
allow_org_create = false
auto_assign_org = true
auto_assign_org_role = Viewer

[auth.anonymous]
enabled = true
org_role = Viewer

[auth.basic]
enabled = true

[auth]
disable_login_form = false
disable_signout_menu = false

[log]
mode = console
level = info

[log.console]
level = info
format = text

[paths]
provisioning = /etc/grafana/provisioning
provisioning dashboards = /etc/grafana/provisioning/dashboards
provisioning datasources = /etc/grafana/provisioning/datasources

[dashboards]
default_home_dashboard_path = /var/lib/grafana/dashboards/default.json

[alerting]
enabled = true
execute_alerts = true

[unified_alerting]
enabled = true

[smtp]
enabled = false
host = localhost:25
user =
password =
;from_address = admin@grafana.localhost
;from_name = Grafana

[metrics]
enabled = true
interval_seconds = 10

[analytics]
reporting_enabled = false
check_for_updates = false

[grafana_net]
url = https://grafana.net
